---
- hosts: all
  become: yes
  tasks:
  - name: installing tomcat
    yum:
      name: tomcat
      state: present
      update_cache: yes
  handlers:
  - name: restart tomcat
    service:
     name: tomcat
     state: restarted
     enabled: yes
